author: ""
category: "Messaging"
summary: "Forward several types of messages as post requests to an arbitrary url"
home: "https://github.com//mod_interact"
url: "git@github.com:agrawalakhil/mod_interact.git"
